name: file-downloader

on:
  push:
    branches: 
      - main

jobs: 
  download-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: run-wget
      run: wget "https://www.msss.gouv.qc.ca/professionnels/statistiques/documents/urgences/Rap_Quotid_SituatUrgence1.pdf"

    - name: commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add *.pdf 
        git mv "Rap_Quotid_SituatUrgence1.pdf" "pdf/urgence.pdf"
        git commit -am "Scheduled Github Action on $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
